name: Hourly EDS Permission Update

on:
  workflow_dispatch: # Allows manual triggering of the workflow

  schedule:
    # Runs at the beginning of every hour (e.g., 00:00, 01:00, 02:00, etc.)
    - cron: '*/5 * * * *' # will run on the default branch

jobs:
  run-hourly-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      
      - name: Run JavaScript file
        run: node tools/importer/eds-permission-cron.js
